"""empty message

Revision ID: 16512d6366a
Revises: 4c0e4c162d
Create Date: 2015-12-04 14:56:21.944826

"""

# revision identifiers, used by Alembic.
revision = '16512d6366a'
down_revision = '4c0e4c162d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kv')
    ### end Alembic commands ###
