"""empty message

Revision ID: 4c0e4c162d
Revises: 4f75df523f8
Create Date: 2015-12-03 16:29:31.297454

"""

# revision identifiers, used by Alembic.
revision = '4c0e4c162d'
down_revision = '4f75df523f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    ### end Alembic commands ###
