"""empty message

Revision ID: 4f75df523f8
Revises: None
Create Date: 2015-12-03 14:26:36.906496

"""

# revision identifiers, used by Alembic.
revision = '4f75df523f8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bar', sa.Integer(), nullable=False),
    sa.Column('baz', sa.Text(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foo')
    op.drop_table('basket')
    ### end Alembic commands ###
